version: '3'
services:
  oracle-polrouteds:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracle-polrouteds
    environment:
      - ORACLE_SID=PolRouteDS
      - ORACLE_PWD=PASSPASS
    volumes:
      - ./scripts:/tmp/scripts
      - ./data:/opt/oracle/oradata
    ports: 
      - "1521:1521"
      - "5500:5500"
    